global:
  scrape_interval: 30s
  evaluation_interval: 30s

otlp:
  promote_resource_attributes:
    - service.name
    - service.instance.id
    - process.pid
    - process.creation.time
    - azure.blobfuse.monitor.source
    - cicd.pipeline.run.id
    - cicd.pipeline.name
    - vcs.ref.head.revision
    - github.run.attempt

scrape_configs: []